/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.cpp                                           */
/*  DATE        :Mon, Sep 05, 2011                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif



void HardwareSetup(void)
{
/*
  LVD.CR.BYTE = 0;
  LVD.CR.BIT.LVDE   = 1;
  LVD.CR.BIT.LVDSEL = 1;
  LVD.CR.BIT.LVDRE  = 1;
  LVD.CR.BIT.LVDDE  = 1;
  LVD.CR.BIT.LVDUE  = 1;
  LVD.SR.BYTE = 0;
  LVD.SR.BIT.LVDDF = 1;
  LVD.SR.BIT.LVDUF = 1;
*/

}
