/***********************************************************************/
/*                                                                     */
/*  FILE        :TankController.cpp                                    */
/*  DATE        :Mon, Sep 05, 2011                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "suicide.hpp"
#include "serial_communication.hpp"
#include "command_manager.hpp"
#include "commands.hpp"
#include "display.hpp"
#include "eeprom.hpp"
#include "rtc.hpp"
#include "thermometer.hpp"
#include "watch_dog.hpp"
#include "heater.hpp"
#include "cooler.hpp"
#include "light.hpp"
#include "tank_status.hpp"
#include "wait.hpp"
#include "alert.hpp"
#include "format_string.hpp"
#include <string>

using namespace util;
using namespace tank_controller;
using namespace tank_controller::commands;

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

const unsigned int setting_address = 0x00;

void measure(tank_status& status, const rtc& clock, const thermometer& thermo)
{
    status.current_time = clock.get();
	status.current_temperature = thermo.measure();
}

void main(void)
{   
    serial_communication& s = serial_communication::get_instance();
    s.write_line("---------------------------");
    s.write_line("      tank controller");
    s.write_line("---------------------------");
    s.write_line("initializing devices...");
    
	//SSR
	heater h;
	cooler c;
	light l;
	
    //ウォッチドッグ
    watch_dog dog;
    s.write_line("watchdog ok");
	
    //温度計
	thermometer thermo;
    s.write_line("thermometer ok");
    
    //EEPROMとRTC
    i2c& i = i2c::get_instance();
    eeprom rom(i);
    s.write_line("eeprom ok");
    rtc clock(i);
    s.write_line("rtc ok");
    
    //LCD
    //display d;
    //d.write_line(0, string("Hello!"));
    s.write_line("lcd ok");
    
    //水槽の状態
    s.write_line("initializing status...");
    bool e = dog.is_error_occured_in_previous_execution();
    if(e)
    {
        s.write_line("error occured in previous execution!");
        alert();
    }
    tank_status status = rom.load<tank_status>(setting_address);
    status.is_crashed = e;
    measure(status, clock, thermo);
    
    //コマンド管理
    command_manager cmmgr;
    
    get_command getc(status);
    set_command setc(status, clock);
    save_command savec(status, rom, setting_address);
    help_command helpc;
    halt_command haltc;
    default_command defaultc;
    
    s.register_receiver(cmmgr);
    cmmgr.register_command(getc);
    cmmgr.register_command(setc);
    cmmgr.register_command(savec);
    cmmgr.register_command(helpc);
    cmmgr.register_command(haltc);
    cmmgr.register_command(defaultc); 
    
    //初期化完了
    s.write_line("initialize complete");
    s.write_line("---------------------------");
    cmmgr.show_command_request_character(s);
    
    dog.run();
    while(true)
    {
        //状態の更新
		measure(status, clock, thermo);
        
        dog.watch();
		
		//SSRの切り替え
		status.update_switches();
		status.is_heater_on() ? h.on() : h.off();
		status.is_cooler_on() ? c.on() : c.off();
		status.is_light_on() ? l.on() : l.off();
        
        dog.watch();
        
        //LCDの更新
        //ここでLCDを更新
        
        dog.watch();
        
        //500msウェイト
        for(int i = 0; i < 10; i++)
        {
            cmmgr.execute(s);   //コマンドの実行
    		dog.watch();
            wait(50);
        }
        
        dog.watch();
    }
    
    serial_communication::delete_instance();
    i2c::delete_instance();
}

#ifdef __cplusplus
void abort(void)
{
    suicide();
}
#endif
